spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        #sqlserver
        driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
        #mysql
        #driverClassName: com.mysql.jdbc.Driver
        druid:
            first:  #数据源1
                #sqlserver url
                url: jdbc:sqlserver://localhost:1433;DatabaseName=jjtech_db
                #mysql url
                #url: jdbc:mysql://localhost:3306/jjtech_db?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
                username: sa
                password: 123456
            initial-size: 10
            max-active: 100
            min-idle: 10
            max-wait: 60000
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            validation-query: SELECT 1
            validation-query-timeout: 5
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            stat-view-servlet:
                enabled: true
                url-pattern: /druid/*
                #login-username: admin
                #login-password: admin
            filter:
                stat:
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: true
                wall:
                    config:
                        multi-statement-allow: true